---
- name: Restart controller service
  become: true
  systemd:
    name: syncdrive-ctlr
    state: restarted
    daemon_reload: true

- name: Restart fluent-bit
  become: true
  systemd:
    name: fluent-bit
    state: restarted

- name: Restart chrony
  become: true
  systemd:
    name: chrony
    state: restarted
