---
- name: Restart camera services
  become: true
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: true
  loop:
    - syncdrive-recorder
    - syncdrive-uploader
    - syncdrive-cam-api

- name: Restart chrony
  become: true
  systemd:
    name: chrony
    state: restarted

- name: Restart rsyslog
  become: true
  systemd:
    name: rsyslog
    state: restarted
