[cameras]
melb-01-cam-01 ansible_host=melb-01-cam-01
melb-01-cam-02 ansible_host=melb-01-cam-02
melb-01-cam-03 ansible_host=melb-01-cam-03

[controllers]
melb-01-ctlr ansible_host=melb-01-ctlr

[pis:children]
cameras
controllers

[pis:vars]
ansible_user=pi
ansible_python_interpreter=/usr/bin/python3
